# ============================================================
# File: prep_mechanism_threshold_analysis.R
#
# Purpose:
#   Construct table-ready summaries that compare *analytic vigilance thresholds*
#   against *empirical hypervigilance values* measured on discretized LA/LL grids.
#
#   These helpers power Fig 4E and related tables by answering:
#     - What happens to hypervigilance just below vs just above λA* ?
#     - What happens just below vs just above λL* ?
#     - What happens when crossing the diagonal πS = K / D boundary?
#
# Key idea:
#   Analytic thresholds (λA*, λL*, πS*) rarely fall *exactly* on the discretized grid.
#   Therefore, we:
#     1) Compute the analytic threshold
#     2) Identify the nearest grid points just below and just above it
#     3) Compare hypervigilance rates across that crossing
#
# Notes:
#   - NO simulations occur here.
#   - This module strictly *post-processes* the grid generated by
#     `hypervigilance_grid_by_Kratio_by_model()`.
#   - All summaries are robust to missing grid points.
# ============================================================

# ---- Dependencies ----------------------------------------------------------
# Shared defaults (N, D, d, etc.)
source("R/core/shared_config.R")

# Model scenario definitions (labels, variants)
source("R/helpers/utils_model_scenarios.R")

# Grid builder used upstream
source("R/plotting/env_heatmaps/00_data_prep_environment_heatmap_data.R")

suppressPackageStartupMessages({
  library(dplyr)
  library(purrr)
  library(tidyr)
  library(tibble)
  library(rlang)
})


# =============================================================================
# Column-detection and grid-navigation helpers
# =============================================================================

# Detect which column identifies the model.
# Some pipelines use `model_label`, others use `model`.
detect_model_column <- function(df) {
  for (candidate in c("model_label", "model")) {
    if (candidate %in% names(df)) return(candidate)
  }
  stop("Could not detect a model column; expected 'model_label' or 'model'.")
}

# Pick a default slice value when none is supplied.
# Preference order:
#   - Explicitly meaningful values (e.g., 0.2, 0.3)
#   - Otherwise, the midpoint of the available grid
pick_default_slice <- function(values, prefer = c(0.2, 0.3)) {
  uniq_vals <- sort(unique(values))
  if (length(uniq_vals) == 0) return(NA_real_)
  preferred <- intersect(prefer, uniq_vals)
  if (length(preferred) > 0) return(preferred[[1]])
  uniq_vals[ceiling(length(uniq_vals) / 2)]
}

# Find the largest grid value <= target
calc_floor <- function(target, grid) {
  if (is.na(target)) return(NA_real_)
  grid <- sort(unique(grid[!is.na(grid)]))
  if (length(grid) == 0 || target < min(grid)) return(NA_real_)
  candidates <- grid[grid <= target]
  if (length(candidates) == 0) return(NA_real_)
  max(candidates)
}

# Find the smallest grid value >= target
calc_ceil <- function(target, grid) {
  if (is.na(target)) return(NA_real_)
  grid <- sort(unique(grid[!is.na(grid)]))
  if (length(grid) == 0 || target > max(grid)) return(NA_real_)
  candidates <- grid[grid >= target]
  if (length(candidates) == 0) return(NA_real_)
  min(candidates)
}

# Safely pull a value from a data frame that might be empty
safe_pull <- function(data, column) {
  if (nrow(data) == 0) return(NA_real_)
  data[[column]][1]
}


# =============================================================================
# Vertical threshold analysis: crossing λA*
# =============================================================================
# Question answered:
#   Holding λL fixed, how does hypervigilance change as λA crosses λA* = K / D ?
#
# Interpretation:
#   This corresponds to the *preventative vigilance threshold* in safe states.
# =============================================================================

vertical_threshold_summary <- function(
    df,
    lambda_l_slice = NULL,
    rate_column = "HypervigilanceRate_all"
) {
  df <- tibble::as_tibble(df)
  model_col <- detect_model_column(df)

  if (!(rate_column %in% names(df))) {
    stop(sprintf("Column '%s' is missing from the supplied data frame.", rate_column))
  }

  # Choose which λL slice to examine
  ll_values <- sort(unique(df$LL))
  if (length(ll_values) == 0) return(tibble())

  slice_value <- lambda_l_slice %||% pick_default_slice(ll_values)
  if (!slice_value %in% ll_values) {
    stop(sprintf("lambda_l_slice must be one of: %s", paste(ll_values, collapse = ", ")))
  }

  # Restrict to that horizontal slice
  df_slice <- df %>% filter(LL == slice_value)
  la_grid <- sort(unique(df_slice$LA))
  if (length(la_grid) == 0) return(tibble())

  rate_sym <- rlang::sym(rate_column)

  # For each model × cost, compute analytic λA*
  combos <- df_slice %>%
    transmute(
      model = as.character(.data[[model_col]]),
      vigilance_cost = K,
      D
    ) %>%
    distinct() %>%
    arrange(model, vigilance_cost) %>%
    mutate(
      lambda_a_star  = vigilance_cost / D,
      lambda_a_below = purrr::map_dbl(lambda_a_star, calc_floor, grid = la_grid),
      lambda_a_above = purrr::map_dbl(lambda_a_star, calc_ceil,  grid = la_grid)
    )

  # Lookup table: hv at each grid LA
  hv_lookup <- df_slice %>%
    transmute(
      model = as.character(.data[[model_col]]),
      vigilance_cost = K,
      LA,
      hv_value = !!rate_sym
    )

  hv_below <- hv_lookup %>% rename(lambda_a_below = LA, hv_below = hv_value)
  hv_above <- hv_lookup %>% rename(lambda_a_above = LA, hv_above = hv_value)

  combos %>%
    left_join(hv_below, by = c("model", "vigilance_cost", "lambda_a_below")) %>%
    left_join(hv_above, by = c("model", "vigilance_cost", "lambda_a_above")) %>%
    mutate(
      delta_hv = if_else(
        is.na(hv_below) | is.na(hv_above),
        NA_real_,
        hv_above - hv_below
      ),
      lambda_l_slice = slice_value
    ) %>%
    select(
      model, vigilance_cost, lambda_l_slice,
      lambda_a_star,
      lambda_a_below, hv_below,
      lambda_a_above, hv_above,
      delta_hv
    )
}


# =============================================================================
# Horizontal threshold analysis: crossing λL*
# =============================================================================
# Question answered:
#   Holding λA fixed, how does hypervigilance change as λL crosses
#   λL* = 1 − K / D ?
#
# Interpretation:
#   This corresponds to the *reactive persistence threshold* in stressed states.
# =============================================================================

horizontal_threshold_summary <- function(
    df,
    lambda_a_slice = NULL,
    rate_column = "HypervigilanceRate_all"
) {
  df <- tibble::as_tibble(df)
  model_col <- detect_model_column(df)

  if (!(rate_column %in% names(df))) {
    stop(sprintf("Column '%s' is missing from the supplied data frame.", rate_column))
  }

  la_values <- sort(unique(df$LA))
  if (length(la_values) == 0) return(tibble())

  slice_value <- lambda_a_slice %||% pick_default_slice(la_values)
  if (!slice_value %in% la_values) {
    stop(sprintf("lambda_a_slice must be one of: %s", paste(la_values, collapse = ", ")))
  }

  df_slice <- df %>% filter(LA == slice_value)
  ll_grid <- sort(unique(df_slice$LL))
  if (length(ll_grid) == 0) return(tibble())

  rate_sym <- rlang::sym(rate_column)

  combos <- df_slice %>%
    transmute(
      model = as.character(.data[[model_col]]),
      vigilance_cost = K,
      D
    ) %>%
    distinct() %>%
    arrange(model, vigilance_cost) %>%
    mutate(
      lambda_l_star  = 1 - vigilance_cost / D,
      lambda_l_below = purrr::map_dbl(lambda_l_star, calc_floor, grid = ll_grid),
      lambda_l_above = purrr::map_dbl(lambda_l_star, calc_ceil,  grid = ll_grid)
    )

  hv_lookup <- df_slice %>%
    transmute(
      model = as.character(.data[[model_col]]),
      vigilance_cost = K,
      LL,
      hv_value = !!rate_sym
    )

  hv_below <- hv_lookup %>% rename(lambda_l_below = LL, hv_below = hv_value)
  hv_above <- hv_lookup %>% rename(lambda_l_above = LL, hv_above = hv_value)

  combos %>%
    left_join(hv_below, by = c("model", "vigilance_cost", "lambda_l_below")) %>%
    left_join(hv_above, by = c("model", "vigilance_cost", "lambda_l_above")) %>%
    mutate(
      delta_hv = if_else(
        is.na(hv_below) | is.na(hv_above),
        NA_real_,
        hv_above - hv_below
      ),
      lambda_a_slice = slice_value
    ) %>%
    select(
      model, vigilance_cost, lambda_a_slice,
      lambda_l_star,
      lambda_l_below, hv_below,
      lambda_l_above, hv_above,
      delta_hv
    )
}


# =============================================================================
# Diagonal threshold analysis: crossing πS = K / D
# =============================================================================
# Question answered:
#   How does hypervigilance change when the *overall stress probability*
#   πS = LA / (LA + LL) crosses the analytic indifference boundary?
#
# Interpretation:
#   This captures the *time-averaged vigilance threshold* across environments.
# =============================================================================

diagonal_threshold_summary <- function(
    df,
    rate_column = "HypervigilanceRate_all"
) {
  df <- tibble::as_tibble(df)
  model_col <- detect_model_column(df)

  if (!(rate_column %in% names(df))) {
    stop(sprintf("Column '%s' is missing from the supplied data frame.", rate_column))
  }

  df <- df %>%
    mutate(pi_S = if_else((LA + LL) <= 0, NA_real_, LA / (LA + LL)))

  combos <- df %>%
    transmute(
      model = as.character(.data[[model_col]]),
      vigilance_cost = K,
      D,
      target_pi_S = K / D
    ) %>%
    distinct() %>%
    arrange(model, vigilance_cost)

  if (nrow(combos) == 0) return(tibble())

  summaries <- purrr::map_dfr(seq_len(nrow(combos)), function(i) {
    row <- combos[i, ]

    subset <- df %>%
      filter(
        .data[[model_col]] == row$model,
        K == row$vigilance_cost,
        !is.na(pi_S)
      )

    below <- subset %>%
      filter(pi_S <= row$target_pi_S) %>%
      arrange(desc(pi_S)) %>%
      slice_head(n = 1)

    above <- subset %>%
      filter(pi_S >= row$target_pi_S) %>%
      arrange(pi_S) %>%
      slice_head(n = 1)

    tibble(
      model = row$model,
      vigilance_cost = row$vigilance_cost,
      target_pi_S = row$target_pi_S,

      lambda_a_below = safe_pull(below, "LA"),
      lambda_l_below = safe_pull(below, "LL"),
      pi_s_below = safe_pull(below, "pi_S"),
      hv_below = safe_pull(below, rate_column),

      lambda_a_above = safe_pull(above, "LA"),
      lambda_l_above = safe_pull(above, "LL"),
      pi_s_above = safe_pull(above, "pi_S"),
      hv_above = safe_pull(above, rate_column)
    )
  })

  summaries %>%
    mutate(
      delta_hv = if_else(
        is.na(hv_below) | is.na(hv_above),
        NA_real_,
        hv_above - hv_below
      )
    )
}


# =============================================================================
# Master entry point
# =============================================================================
# Runs the full threshold analysis using project defaults and returns
# all three summaries as a named list.
# =============================================================================

run_threshold_analysis <- function() {
  states   <- c("K", "Kd", "C", "CD")
  T_steps <- 10
  N_agents <- validate_default("N")
  C <- 0
  D <- validate_default("D")
  d <- validate_default("d")

  hv_env_models <- hypervigilance_grid_by_Kratio_by_model(
    model_scenarios = default_env_model_scenarios,
    D = D, C = C, d = d,
    T_steps = T_steps,
    states = states,
    N_agents = N_agents,
    grid_step = 0.1,
    ratio_step = 0.2
  )

  invisible(list(
    vertical   = vertical_threshold_summary(hv_env_models),
    horizontal = horizontal_threshold_summary(hv_env_models),
    diagonal   = diagonal_threshold_summary(hv_env_models)
  ))
}

# -----------------------------------------------------------------------------
# Transformation summary:
#   - Vertical:  λA* crossings at fixed λL
#   - Horizontal: λL* crossings at fixed λA
#   - Diagonal:  πS = K/D crossings across the full grid
#
# Each comparison uses *nearest grid neighbors* so all differences
# reflect actual simulated data, not interpolation.
# -----------------------------------------------------------------------------

