# ===================================================================================================
# File: prep_environment_heatmap_data.R
# Purpose:
#   Build the LA/LL hypervigilance grids AND the shared faceted heatmap builder used by
#   (almost) every downstream environment/mechanism figure.
#
# In plain language:
#   - We create a grid over environments, where each environment cell is defined by:
#       LA = stressor appearance probability/rate  (Î»A)
#       LL = stressor disappearance probability/rate (Î»L)
#   - For each cell we:
#       1) compute an optimal policy (DP) for a chosen model + cost parameters
#       2) simulate agents following that policy
#       3) compute hypervigilance statistics (including a canonical â€œsafe/no-stressorâ€ HV rate)
#   - We optionally repeat this for multiple K values (via K/D ratios) so we can facet by cost.
#   - We provide a plotting helper that standardizes:
#       axes, facet layout, labels, legend, and optional row-title layout used in paper panels
#
# Inputs:
#   - DP policy + simulation engines for basic and health models
#   - hv normalization/metadata helpers (prep_hypervigilance_data.R, hv_rate_helpers.R)
#   - model scenario definitions (utils_model_scenarios.R)
#   - shared plot layout helpers and subtitle utilities
#
# Outputs:
#   - Tables (data.frames) like hypervigilance_grid* that downstream scripts can reuse
#   - ggplot objects generated by plot_env_heatmap_faceted_by_K()
#
# Notes:
#   - Mostly pure transformations; minimal I/O (save_hv_matrix_table is the exception).
#   - Heavily annotated to make each aggregation decision reviewer-friendly.
# ===================================================================================================


# ---------------------------------------------------------------------------------------------------
# Dependencies (sourced project code)
# ---------------------------------------------------------------------------------------------------
# utils_subtitles.R:
#   - append_h0_to_subtitle(): ensures health ceiling (h0) appears in subtitles when relevant
# utils_model_scenarios.R:
#   - default_env_model_scenarios: list of model variants/scenarios to facet by rows
#   - merge_model_args(): merges base policy/sim args with scenario-specific overrides
# prep_hypervigilance_data.R:
#   - extract_hypervigilance_metadata()/vectors(): normalizes columns across sim outputs
# utils_plot_layout.R:
#   - wrap_env_heatmap_with_row_title(): custom grob wrapper to add row title annotation
# hv_rate_helpers.R:
#   - compute_hv_rates_from_agent_data(): canonical HV rates (safe/no-stressor filtering)
source("R/plotting/_shared/utils_subtitles.R")
source("R/helpers/utils_model_scenarios.R")
source("R/core/hypervigilance/00_data_prep_hypervigilance_data.R")
source("R/plotting/_shared/utils_plot_layout.R")
source("R/core/hv_rate_helpers.R")

# ---------------------------------------------------------------------------------------------------
# Packages
# ---------------------------------------------------------------------------------------------------
# dplyr: data wrangling
# ggplot2: plotting
# future.apply: parallel evaluation of grid cells
#
# Note: parallelism matters here because a full LAÃ—LLÃ—K grid can be expensive.
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(future.apply)
})


# ===================================================================================================
# 1) hypervigilance_grid(): compute one LAÃ—LL grid for a FIXED K
# ===================================================================================================

#' Build a tidy LA/LL grid for a fixed K cost.
#'
#' @param K vigilance cost
#' @param C baseline damage parameter (often â€œrelaxed baseline costâ€)
#' @param D damage parameter for vigilant agents (damage when stressor hits under vigilance)
#' @param d damage parameter for relaxed agents (damage when stressor hits under relaxation)
#' @param T_steps integer horizon length
#' @param states character vector of state labels (used by `mem_compute_policy` in basic model)
#' @param N_agents number of agents to simulate per LA/LL cell
#' @param grid_step numeric resolution for LA/LL axis
#' @param model character("basic","health")
#' @param policy_args list forwarded to `mem_compute_policy` (health model configuration, etc.)
#' @param sim_args list forwarded to `mem_simulate_agents` (health sim settings, etc.)
#' @return data.frame with hv statistics per grid cell
#'
#' @description
#'   For every (LA,LL) cell in a square grid:
#'     - compute optimal policy (cached)
#'     - simulate agents (cached)
#'     - compute HV rates and â€œprevent/spillâ€ metadata
#'
#' Parallelism:
#'   - Uses future.apply::future_lapply() so each grid cell can be evaluated concurrently.
hypervigilance_grid <- function(
    K, C, D, d,                 # cost/damage parameters
    T_steps,                    # time horizon
    states,                     # DP state labels for basic model (ignored by health implementation if unused)
    N_agents,                   # simulation sample size per cell
    grid_step = 0.1,            # LA/LL resolution (0..0.5)
    model = c("basic", "health"),
    policy_args = list(),
    sim_args    = list()
) {
  # Match and validate model identifier
  model <- match.arg(model)

  # Constraint check:
  # Many DP formulations in this project assume a parameter regime where vigilance
  # is not dominated by relaxation in all cases. The inequality:
  #   K + d <= C + D
  # appears to enforce that â€œvigilance cost + relaxed damageâ€ does not exceed
  # â€œbaseline cost + vigilant damageâ€ in a way that could break interpretation.
  # (Exactly why depends on the core model; this is a protective guardrail.)
  if ((K + d) > (C + D)) stop("Require K + d <= C + D.")

  # ---------------------------------------------------------------------------
  # Step 1: Expand the environment grid
  # ---------------------------------------------------------------------------
  # We evaluate LA and LL on a regular lattice.
  # Range is 0..0.5 by default because (in your project) LA/LL are typically
  # interpreted as probabilities per timestep bounded within this range.
  grid <- expand.grid(
    LA = seq(0, 0.5, by = grid_step),
    LL = seq(0, 0.5, by = grid_step),
    KEEP.OUT.ATTRS = FALSE
  )

  # ---------------------------------------------------------------------------
  # Step 2: Evaluate each grid cell (policy + simulation + HV metrics)
  # ---------------------------------------------------------------------------
  # We parallelize over rows of `grid`.
  #
  # future.seed = TRUE:
  #   - ensures reproducible randomness across workers
  #   - crucial because results should not depend on scheduling / worker count
  #
  # future.packages:
  #   - packages that must be available on worker sessions
  #   - mem_* functions and sourced helpers must already be visible in worker env
  rows <- future.apply::future_lapply(
    seq_len(nrow(grid)),
    future.seed = TRUE,
    future.packages = c("dplyr"),
    FUN = function(i) {

      # Pull LA/LL for this cell
      LAi <- grid$LA[i]
      LLi <- grid$LL[i]

      # --- 2A: Compute optimal policy (cached) --------------------------------
      # mem_compute_policy() is expected to:
      #   - use on-disk caching keyed by model+params+policy_args
      #   - return a policy data.frame
      pol <- mem_compute_policy(
        model = model,
        K = K, C = C, D = D, d = d,
        LA = LAi, LL = LLi,
        T_steps = T_steps,
        states = states,
        policy_args = policy_args
      )

      # --- 2B: Simulate agents forward (cached) -------------------------------
      # mem_simulate_agents() is expected to:
      #   - accept policy_df + env params + sim args
      #   - return list(sim$agent_data, sim$agent_stats, ...)
      # The agent_data must contain (possibly normalized later):
      #   time, agent, action, hv, stressor indicator, etc.
      sim <- mem_simulate_agents(
        model = model,
        policy_df = pol,
        LA = LAi, LL = LLi,
        T_steps = T_steps,
        N_agents = N_agents,
        K = K, C = C, D = D, d = d,
        sim_args = sim_args
      )

      # Extract agent-level panel data
      ad <- sim$agent_data

      # --- 2C: Compute canonical HV rates + metadata --------------------------
      # compute_hv_rates_from_agent_data() returns a rich list:
      #   HypervigilanceRate_all
      #   HypervigilanceRate_filtered (canonical: pooled mean on no-stressor rows)
      #   Spread_no_stressor (variability on no-stressor rows)
      #   coverage diagnostics and hv_meta payload
      hv_rates <- compute_hv_rates_from_agent_data(ad, T_steps = T_steps, N_agents = N_agents)

      # hv_meta comes from extract_hypervigilance_metadata() under the hood and
      # may contain breakdowns like:
      #   safe_hv: hv during safe/no-stressor windows
      #   prevent/spill counts: decomposition into preventive vs spillover HV
      hv_meta <- hv_rates$hv_meta

      # For readability
      hv_filtered <- hv_rates$HypervigilanceRate_filtered  # canonical safe-pooled mean
      hv_all      <- hv_rates$HypervigilanceRate_all       # pooled mean over all rows

      # --- 2D: Return one-row summary for this grid cell ----------------------
      # We build a plain data.frame for compatibility and speed in bind_rows().
      data.frame(
        LA = LAi,
        LL = LLi,
        K  = K,
        D  = D,

        # autocorr proxy:
        # In a simple two-state stressor Markov process, a common rough proxy
        # for persistence/autocorrelation is 1 - (LA + LL). We clamp to [0,1]
        # because rates outside that range can occur at edges or unusual inputs.
        autocorr = pmin(pmax(1 - (LAi + LLi), 0), 1),

        # HV metrics used by downstream plots
        HypervigilanceRate_all       = hv_all,
        HypervigilanceRate_filtered  = hv_filtered,

        # Additional hv_meta signals (coalesce missing to 0 for robustness)
        HypervigilanceSafeHV         = dplyr::coalesce(hv_meta$safe_hv, 0),
        HypervigilancePreventCount   = dplyr::coalesce(hv_meta$prevent, 0),
        HypervigilanceSpillCount     = dplyr::coalesce(hv_meta$spill, 0),

        # Diagnostics
        Spread_no_stressor           = hv_rates$Spread_no_stressor,
        Prop_timesteps_included      = dplyr::coalesce(hv_rates$Prop_timesteps_included, 0),
        Prop_agent_timesteps         = dplyr::coalesce(hv_rates$Prop_agent_timesteps, 0),

        stringsAsFactors = FALSE
      )
    }
  )

  # Bind per-cell rows into one large grid table
  dplyr::bind_rows(rows)
}


# ===================================================================================================
# 2) hypervigilance_grid_by_Kratio(): augment LAÃ—LL grid with a sweep over K/D ratio
# ===================================================================================================

#' Sweep K/D ratios across the LA/LL grid to build an augmented dataset.
#'
#' @param D base damage parameter
#' @param C baseline damage parameter
#' @param d relaxed damage
#' @param T_steps integer horizon
#' @param states character vector of DP states
#' @param N_agents number of simulated agents
#' @param grid_step resolution for LA/LL grid
#' @param ratio_step step size for D*K ratio
#' @param model character("basic","health")
#' @param policy_args list forwarded to `mem_compute_policy`
#' @param sim_args list forwarded to `mem_simulate_agents`
#' @return data.frame with hv rates + K ratio metadata
#'
#' @details
#'   This function exists because many environment heatmap figures are faceted by
#'   vigilance cost K. Rather than recomputing separate grids per K manually,
#'   we create a single long dataset with an explicit RatioDK and K column.
#'
#'   RatioDK is used as an â€œinterpretable sweep axisâ€:
#'     K = round(D * RatioDK)
#'   so the cost scale remains comparable across different D settings.
hypervigilance_grid_by_Kratio <- function(
    D, C, d, T_steps, states, N_agents,
    grid_step = 0.1,
    ratio_step = 0.2,
    model = c("basic", "health"),
    policy_args = list(),
    sim_args    = list()
) {
  model <- match.arg(model)

  # ---------------------------------------------------------------------------
  # Step 1: Build augmented grid LA Ã— LL Ã— RatioDK
  # ---------------------------------------------------------------------------
  # RatioDK ranges 0.1..0.9 by default; you can adjust depending on paper design.
  grid <- expand.grid(
    LA      = seq(0, 0.5, by = grid_step),
    LL      = seq(0, 0.5, by = grid_step),
    RatioDK = seq(0.1, 0.9, by = ratio_step),
    KEEP.OUT.ATTRS = FALSE
  ) |>
    # Convert ratio into an integer-ish K so faceting uses stable discrete values.
    dplyr::mutate(K = as.integer(round(D * RatioDK))) |>
    # Enforce same feasibility constraint as before:
    # (drop combinations where K is too large relative to costs/damages)
    dplyr::filter((K + d) <= (C + D))

  # If everything was filtered out (e.g., extreme params), return an empty df
  if (nrow(grid) == 0) return(grid[0, ])

  # ---------------------------------------------------------------------------
  # Step 2: Evaluate each augmented cell (parallel)
  # ---------------------------------------------------------------------------
  rows <- future.apply::future_lapply(
    seq_len(nrow(grid)),
    future.seed = TRUE,
    future.packages = c("dplyr"),
    FUN = function(i) {

      # Parameters for this cell
      LAi <- grid$LA[i]
      LLi <- grid$LL[i]
      Ki  <- grid$K[i]

      # --- 2A: Policy (cached) ------------------------------------------------
      pol <- mem_compute_policy(
        model = model,
        K = Ki, C = C, D = D, d = d,
        LA = LAi, LL = LLi,
        T_steps = T_steps,
        states = states,
        policy_args = policy_args
      )

      # --- 2B: Simulation (cached) -------------------------------------------
      sim <- mem_simulate_agents(
        model = model,
        policy_df = pol,
        LA = LAi, LL = LLi,
        T_steps = T_steps,
        N_agents = N_agents,
        K = Ki, C = C, D = D, d = d,
        sim_args = sim_args
      )

      # Some older codepaths compute hv_rate per-agent in sim$agent_stats.
      # We keep this as an optional extra metric when it exists, but we prefer
      # canonical pooled safe/no-stressor HV from hv_rate_helpers.
      stats <- sim$agent_stats
      ad    <- sim$agent_data

      hv_rates <- compute_hv_rates_from_agent_data(ad, T_steps = T_steps, N_agents = N_agents)
      hv_meta  <- hv_rates$hv_meta
      hv_filtered <- hv_rates$HypervigilanceRate_filtered
      hv_all      <- hv_rates$HypervigilanceRate_all

      # Optional: â€œagent mean hv_rateâ€ if agent_stats has hv_rate column
      hv_rate_stat <- if ("hv_rate" %in% names(stats)) {
        dplyr::coalesce(mean(stats$hv_rate, na.rm = TRUE), NA_real_)
      } else {
        NA_real_
      }

      # One-row summary
      data.frame(
        LA = LAi,
        LL = LLi,
        K  = Ki,
        D  = D,
        RatioDK = grid$RatioDK[i],

        autocorr = pmin(pmax(1 - (LAi + LLi), 0), 1),

        HypervigilanceRate_all       = hv_all,
        HypervigilanceRate_filtered  = hv_filtered,

        # Safe-window HV counts and decomposition (if provided by hv_meta)
        HypervigilanceSafeHV         = dplyr::coalesce(hv_meta$safe_hv, 0),
        HypervigilanceSafeSteps      = dplyr::coalesce(hv_meta$safe_steps, 0),
        HypervigilancePreventCount   = dplyr::coalesce(hv_meta$prevent, 0),
        HypervigilanceSpillCount     = dplyr::coalesce(hv_meta$spill, 0),

        # Optional legacy-style per-agent summary
        HypervigilanceRate_agent_mean = hv_rate_stat,

        # Diagnostics
        Spread_no_stressor           = hv_rates$Spread_no_stressor,
        Prop_timesteps_included      = dplyr::coalesce(hv_rates$Prop_timesteps_included, 0),
        Prop_agent_timesteps         = dplyr::coalesce(hv_rates$Prop_agent_timesteps, 0),

        stringsAsFactors = FALSE
      )
    }
  )

  dplyr::bind_rows(rows)
}


# ===================================================================================================
# 3) hypervigilance_grid_by_Kratio_by_model(): stack grids across model scenarios
# ===================================================================================================

#' Stack env grids across predefined model scenarios.
#'
#' @param model_scenarios list of named scenarios (label + policy/sim args)
#' @param D,C,d,T_steps,states,N_agents same as other grid functions
#' @param grid_step numeric LA/LL resolution
#' @param ratio_step numeric ratio step for K/D
#' @param base_policy_args list merged with scenario-specific policy args
#' @param base_sim_args list merged with scenario-specific sim args
#' @return data.frame stacked across scenario labels for faceted plotting
#'
#' @details
#'   Many figures compare multiple â€œmodel variantsâ€ (e.g., basic vs health,
#   health with/without terminal reward). Each scenario defines:
#     - a model family ("basic" or "health")
#     - policy_args and sim_args overrides
#     - a display label for row facets
#   This function:
#     - runs hypervigilance_grid_by_Kratio() per scenario
#     - adds model_label/model_id/model columns so plotting can facet by rows
#     - stores row order as an attribute for consistent panel layout
hypervigilance_grid_by_Kratio_by_model <- function(
    model_scenarios = default_env_model_scenarios,
    D, C, d, T_steps, states, N_agents,
    grid_step = 0.1,
    ratio_step = 0.2,
    base_policy_args = list(),
    base_sim_args = list()
) {
  if (length(model_scenarios) == 0) stop("model_scenarios must have at least one entry")

  # Determine row facet order (labels) in advance so it stays stable.
  row_levels <- vapply(seq_along(model_scenarios), function(i) {
    lbl <- model_scenarios[[i]]$label
    if (is.null(lbl) || !nzchar(lbl)) paste0("model ", i) else lbl
  }, character(1))

  # Run each scenario and tag it for faceting
  rows <- lapply(seq_along(model_scenarios), function(i) {
    scenario <- model_scenarios[[i]]

    # Default to health if not specified (project convention)
    model <- if (is.null(scenario$model)) "health" else scenario$model

    # Merge base args with scenario overrides.
    # This ensures global settings (like h0) can be supplied once and
    # scenario differences can be minimal.
    pol_args <- merge_model_args(base_policy_args, scenario$policy_args)
    sim_args <- merge_model_args(base_sim_args, scenario$sim_args)

    # Compute scenario grid (may be large; relies on caching + parallelism)
    df <- hypervigilance_grid_by_Kratio(
      D = D, C = C, d = d,
      T_steps = T_steps, states = states, N_agents = N_agents,
      grid_step = grid_step, ratio_step = ratio_step,
      model = model, policy_args = pol_args, sim_args = sim_args
    )
    if (nrow(df) == 0) return(NULL)

    # Add facet identifiers used downstream:
    df$model_label <- row_levels[i]  # human-facing label
    df$model_id    <- i              # numeric id (stable order)
    df$model       <- model          # "basic" or "health"
    df
  })

  # Drop scenarios that produced no rows (e.g., invalid param regimes)
  rows <- Filter(Negate(is.null), rows)
  if (length(rows) == 0) return(data.frame())

  # Stack all scenarios
  out <- dplyr::bind_rows(rows)

  # Ensure model_label is a factor with the intended row order
  out$model_label <- factor(out$model_label, levels = row_levels[row_levels %in% out$model_label])

  # Store row order in an attribute so plotting wrappers can reuse it
  attr(out, "row_levels") <- levels(out$model_label)

  out
}


# ===================================================================================================
# 5) save_hv_matrix_table(): helper to write grid as CSV (optional I/O)
# ===================================================================================================

#' Save the hv matrix table as CSV so other scripts can re-use the same grid without rerunning.
#'
#' @param df data frame produced by the hypervigilance grid helpers
#' @param stem file path stem (without extension)
#' @return path to the written CSV (invisible)
#'
# Why this exists:
#   - Environment grids can be expensive to recompute.
#   - Saving the computed grid enables downstream scripts (or reviewers) to load the
#     exact data used for a figure without rerunning DP+simulation.
save_hv_matrix_table <- function(df, stem = file.path("outputs", "figures", "hv_matrix_over_env")) {
  if (!is.data.frame(df)) stop("df must be a data.frame")

  dir <- dirname(stem)
  if (!dir.exists(dir)) dir.create(dir, recursive = TRUE, showWarnings = FALSE)

  csv_path <- paste0(stem, ".csv")

  # Note: requires readr; ensure itâ€™s attached/imported somewhere in the project.
  readr::write_csv(df, csv_path)

  message("Saved HV matrix table: ", csv_path)
  invisible(csv_path)
}


# ===================================================================================================
